fix(powershell): fix powershell prompt
version-fox/vfox pull request #101
Opened 2024-03-12 08:51 UTC by LordHumphrey

1. Fix powershell prompt has been replaced, just using the original prompt.
2. 获取到原prompt后，先尝试匹配是否是默认[prompt](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_prompts?view=powershell-7.4)，如果是则适用默认方式生成prompt，否则适用自定义方式。
3. 为什么没有直接使用原始prompt？
`"PS $($executionContext.SessionState.Path.CurrentLocation)$('>' * ($nestedPromptLevel + 1)) ";
` 这里的`>`似乎会变化，如果直接返回原始prompt就出现不一致。

2024-03-12 09:33 UTC, aooohan commented on internal/shell/powershell.go
> +    $export = &'{{.SelfPath}}' env -s pwsh
不要去掉`;`

这样改变了原有的行为 ;)

2024-03-12 09:33 UTC, aooohan commented on internal/shell/powershell.go
> +    if ($originalPrompt -like "*PS $($executionContext.SessionState.Path.CurrentLocation)$('>' * ($nestedPromptLevel + 1))*") {
过于麻烦了, 不需要进行判断

2024-03-12 09:35 UTC, aooohan commented on internal/shell/powershell.go
> +$originalPrompt = & $function:prompt
这一步为什么要执行呢, 我们可以不执行啊, 对不对? 直接放到我们自己的prompt最后 去执行不就行啦?

2024-03-12 09:36 UTC, aooohan commented
思路是对的, 就是写的有些复杂了.
```powershell
$originalPrompt = $function:prompt;
function prompt {
    $export = &'{{.SelfPath}}' env -s pwsh;
    if ($export) {
        Invoke-Expression -Command $export;
    }
    &$originalPrompt;
}
```

2024-03-12 10:12 UTC, LordHumphrey commented
> 思路是对的, 就是写的有些复杂了.
> 
> ```powershell
> $originalPrompt = $function:prompt;
> function prompt {
>     $export = &'{{.SelfPath}}' env -s pwsh;
>     if ($export) {
>         Invoke-Expression -Command $export;
>     }
>     &$originalPrompt;
> }
> ```

好的，感谢您的指导，请问我接下来是再发起一个pr吗

2024-03-12 10:16 UTC, aooohan commented
> > 思路是对的, 就是写的有些复杂了.
> > 
> > ```powershell
> > $originalPrompt = $function:prompt;
> > function prompt {
> >     $export = &'{{.SelfPath}}' env -s pwsh;
> >     if ($export) {
> >         Invoke-Expression -Command $export;
> >     }
> >     &$originalPrompt;
> > }
> > ```
> 
> 好的，感谢您的指导，请问我接下来是再发起一个pr吗

在这个上面修改就行，把代码回退，重新修改就可以

2024-03-12 10:28 UTC, LordHumphrey commented on internal/shell/powershell.go
> +$originalPrompt = & $function:prompt
我试了，必须在进入prompt函数之前执行`& $function:prompt`,如果按照您的写法，会出现一下错误
```powershell
Line |
 334 |   Invoke-Expression "$(vfox activate pwsh)"
     |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Unexpected token 'function' in expression or statement.
```

2024-03-13 01:41 UTC, aooohan commented on internal/shell/powershell.go
> +$originalPrompt = & $function:prompt
报错是因为你没有加`;`吧, 我本地试了一下没问题.

2024-03-13 02:12 UTC, aooohan requested changes

2024-03-13 02:12 UTC, aooohan commented on internal/shell/powershell.go
> +$originalPrompt = & $function:prompt
```suggestion
$originalPrompt = $function:prompt;
```

2024-03-13 02:12 UTC, aooohan commented on internal/shell/powershell.go
> +    return $originalPrompt;
```suggestion
    &$originalPrompt;
```

2024-03-13 02:15 UTC, merged

2024-03-13 02:17 UTC, aooohan commented
@LordHumphrey 感谢贡献 👍

2024-03-13 02:18 UTC, LordHumphrey commented
> @LordHumphrey 感谢贡献 👍

您太客气了，是我谢谢您，第一次给开源项目提PR，您给的帮助很大~